//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemler
    {
        public int id { get; set; }
        public Nullable<int> islemId { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public Nullable<int> rezervasyonId { get; set; }
        public Nullable<System.DateTime> guncellemeTarihi { get; set; }
        public Nullable<System.DateTime> silmeTarihi { get; set; }
        public Nullable<System.DateTime> olusturmaTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual islemTuru islemTuru { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual rezervasyon rezervasyon { get; set; }
    }
}
