//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rezervasyon()
        {
            this.islemler = new HashSet<islemler>();
        }
    
        public int id { get; set; }
        public Nullable<int> oda_id { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<System.DateTime> giris_tarihi { get; set; }
        public Nullable<System.DateTime> cikis_tarihi { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public string tc { get; set; }
        public string telNo { get; set; }
        public Nullable<System.DateTime> olusturmaTarihi { get; set; }
        public Nullable<System.DateTime> guncellemeTarihi { get; set; }
        public Nullable<System.DateTime> silmeTarihi { get; set; }
        public Nullable<bool> aktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islemler> islemler { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual odalar odalar { get; set; }
    }
}
